### ISSUE TITLE
Implement World Data Containers

### ISSUE THREAD

**Issue by Lathie** [GalaxionTeam/galaxion-engine#19]
This is a larger task can can be divided into several subtasks. The gist of it is that we want to implement data structures that hold data about the game (player, world, room, items) 

- [x] Create a folder for `assets` and move player.py in there https://github.com/GalaxionTeam/galaxion-engine/pull/18
- [x] [Create World and Room classes to contain state about the world](https://github.com/GalaxionTeam/galaxion-engine/issues/20)
- [ ] [Refactor existing update.py code to use the new world system instead of just being coordinates](https://github.com/GalaxionTeam/galaxion-engine/issues/21)
- [ ] [Create Item class, modify player and room code to support items](https://github.com/GalaxionTeam/galaxion-engine/issues/22)
- [ ] [Refactor update.py to support item logic](https://github.com/GalaxionTeam/galaxion-engine/issues/23)
- [ ] [Create a test world with rooms and items to play with and test on](https://github.com/GalaxionTeam/galaxion-engine/issues/24)
